### PR TITLE
Update Gumbel intersection to provide approximation choices and support broadcasting.

### PR DESCRIPTION
**Pull request by dhruvdcoder**
Added an option `approximation_mode` (options: None, 'clipping', 'nextafter') to specify the kind of approximation one would like to perform to satisfy the inequality `max(a,b) < beta * logaddexp(a/beta,b/beta)`. 

That being said both 'clipping' and 'nextafter' produce inaccurate gradients (see: `tests/modules/intersection/test_gumbel_intersection.py::test_intersection_all_input_ranges_grad_value`) compared to `None`. Hence, we will have to try both in practice and pick the one that works best.

### CODE REVIEW

**Comment by mboratko** [comment]
After additional thought, I'm not sure we need the `nextafter` method.
The clipping method could similarly be restricted to the forward pass only. This approach only changes the output value in cases where the direct calculation would have yielded an error, and it does so using the smallest number that achieves this goal.

**Comment by mboratko** [comment]
In fact, the gradients with the clipping method (if the clipped parts are only applied to the forward pass) are probably more accurate than without it. For MSE loss, for example, the gradient of the logsumexp will be multiplied by the output, and the clipped output is more accurate than the non-clipped output.

**Comment by dhruvdcoder** [comment]
So I should change the 'clipping' method to use different values for the forward (clipped) and backward passes (non-clipped).

**Comment by mboratko** [comment]
I think so, and I guess remove the nextafter method entirely. I cannot think of a situation where it would yield a better result than the clipping method, in fact I think one can prove that the clipping method (with different values for the forward / backward pass) is always better than either non-clipping and nextafter.

**Pull request merged**
